// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	client "github.com/aradia23/checkout-payment-gateway-challengeo/internal/client"
	mock "github.com/stretchr/testify/mock"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: req
func (_m *ClientInterface) Authorize(req client.AutherizaionRequest) (client.AutherizaionResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 client.AutherizaionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(client.AutherizaionRequest) (client.AutherizaionResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(client.AutherizaionRequest) client.AutherizaionResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(client.AutherizaionResponse)
	}

	if rf, ok := ret.Get(1).(func(client.AutherizaionRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
